server:
  port: 8001

spring:
  application:
    name: short-link-project
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 123.249.120.106
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 123.249.120.106:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  rabbitmq:
    host: 123.249.120.106
    port: 5672
    virtual-host: /
    username: glh
    password: 123321
short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: b7b2eb2f35da6ae61a33e8f30ee6902d
  goto-domain:
    white-list:
      enable: false
      names: '拿个offer,知乎，掘金，博客园'
      details:
        - nageoffer.com
        - juejin.cn
        - zhihu.com
        - cnblogs.com
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

