server:
  port: 8001

spring:
  application:
    name: short-link-project
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 47.95.168.146
      port: 6379
      password: 009217
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  mvc:
    view:
      prefix: /templates/
      suffix: .html
short-link:
  domain:
    default: nurl.ink:8001
  stats:
    #高德api的key
    amqp-key: b7b2eb2f35da6ae61a33e8f30ee6902d
  goto-domain:
    white-list:
      enable: false
      names: '拿个offer,知乎，掘金，博客园'
      details:
        - nageoffer.com
        - juejin.cn
        - zhihu.com
        - cnblogs.com
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

